/* AUTO-GENERATED by scripts/build-meta.mjs — do not edit by hand. */
export default {
  "/episodes/ep-015": {
    "title": "SEND ME ANONYMOUS MESSAGES — Hot & Juicy Podcast",
    "description": "We open up the anonymous message box and read the most honest, brutal, and hilarious messages from our audience. Nothing is off limits.",
    "image": "https://i.ytimg.com/vi/PMP3Tqt0lUk/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-014": {
    "title": "AFRICAN BLIND DATE SHOW — Hot & Juicy Podcast",
    "description": "We play matchmaker in the very first Hot & Juicy blind date special. Awkward moments, genuine connections, and lots of laughs.",
    "image": "https://i.ytimg.com/vi/J2lohJkx8vs/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-013": {
    "title": "KENYANS IN QATAR EXPOSED — Black Tax, Fear & Going Home Talks — Hot & Juicy Podcast",
    "description": "We expose the real talk about Kenyans living in Qatar — black tax, the fear of going back home, and the uncomfortable truths nobody says out loud.",
    "image": "https://i.ytimg.com/vi/K-_bfFAOwJk/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-012": {
    "title": "SHARP BOYS EXPOSED — The Dirty Game Behind The Hustle — Hot & Juicy Podcast",
    "description": "We expose the sharp boys — the dirty game behind the hustle that everyone in the diaspora knows about but rarely talks about openly.",
    "image": "https://i.ytimg.com/vi/17uCk6-19Bw/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-011": {
    "title": "ANDREW KIBE: WHY KENYAN MEN HAVE ABANDONED CLUBS IN 2025 ft HAO — Hot & Juicy Podcast",
    "description": "Andrew Kibe joins us to break down why Kenyan men are abandoning clubs in 2025. A deep dive into changing nightlife culture, relationships, and the new social",
    "image": "https://i.ytimg.com/vi/L7rfxA9LV5U/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-010": {
    "title": "From Gulf Money to Mjengo Hustle — Hot & Juicy Podcast",
    "description": "The journey from making Gulf money to the mjengo hustle — we talk about the shift, the reality check, and what it really means to build something back home.",
    "image": "https://i.ytimg.com/vi/bhcHPfPjOK0/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-009": {
    "title": "WHO IS MOST LIKELY ft HAO PODCAST — Hot & Juicy Podcast",
    "description": "We team up with the HAO Podcast for a hilarious game of Who Is Most Likely. Expect chaos, unexpected confessions, and plenty of laughs.",
    "image": "https://i.ytimg.com/vi/JU8yJMmTNGs/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-008": {
    "title": "Andrew Kibe On Njugush And Wakafinywa Breakup — Hot & Juicy Podcast",
    "description": "Andrew Kibe joins us to break down the Njugush and Wakafinywa breakup — the drama, the reactions, and what it says about Kenyan content creation.",
    "image": "https://i.ytimg.com/vi/TDExkYh3drQ/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-007": {
    "title": "Are We Living in The Matrix? Simulation Theory Explained — Hot & Juicy Podcast",
    "description": "We dive deep into simulation theory — are we living in a simulation? We debate the evidence, the philosophers, and the mind-bending possibilities.",
    "image": "https://i.ytimg.com/vi/l6Y2hEkz1_8/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-006": {
    "title": "Andrew Kibe Breaks Silence on BBC Interview Controversy — Hot & Juicy Podcast",
    "description": "Andrew Kibe finally breaks his silence on the BBC interview controversy that had the internet talking. We get the full story, no filters.",
    "image": "https://i.ytimg.com/vi/AAAjCCc77yc/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-005": {
    "title": "He Was a Security Guard Until Sheikh Al Mayassa Discovered Him — Hot & Juicy Podcast",
    "description": "An incredible story of a Kenyan who went from working as a security guard to being discovered by Sheikh Al Mayassa in Qatar. A true rags-to-riches tale.",
    "image": "https://i.ytimg.com/vi/o0nvshL0_7c/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-004": {
    "title": "From Security Guard to Qatar's Highest-Paid Kenyan Artist — Hot & Juicy Podcast",
    "description": "The inspiring story of a Kenyan who went from security guard to becoming Qatar's highest-paid Kenyan artist. A journey of resilience, talent, and determinatio",
    "image": "https://i.ytimg.com/vi/gijC-jIyc2c/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-003": {
    "title": "Food Controversies — Hot & Juicy Podcast",
    "description": "We settle the biggest food debates — ugali vs chapati, nyama choma protocols, and the dishes that divide families. Nothing is off the table.",
    "image": "https://i.ytimg.com/vi/PMP3Tqt0lUk/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-002": {
    "title": "How to Dress & Look Expensive Without Breaking the Bank — Hot & Juicy Podcast",
    "description": "Style and confidence talk — how to dress well and look expensive without breaking the bank. Fashion, fit, and looking the part on a budget.",
    "image": "https://i.ytimg.com/vi/hdsLogtyQjE/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-001": {
    "title": "Hot & Juicy Podcast Is Live! — Hot & Juicy Podcast",
    "description": "A live recording with Mapettco, Kabua, and Keithalfred01 — the conversations everyone is thinking about, happening in real time with the community.",
    "image": "https://i.ytimg.com/vi/OYCwtUXXbm4/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/blog/post-001": {
    "title": "What It Really Means to Be Kenyan in Doha — Hot & Juicy Blog",
    "description": "Living between two worlds — the warmth of Nairobi and the ambition of Qatar. Here's what nobody tells you about the expat experience.",
    "image": "https://hotandjuicypodcast.com/images/blog-what-it-means-kenyan-doha.jpg",
    "type": "article"
  },
  "/blog/post-002": {
    "title": "The Ugali Diaries: What Kenyan Food Says About Who We Are — Hot & Juicy Blog",
    "description": "From the great ugali debate to the politics of chapati at weddings — Kenyan food is more than fuel. It is identity, memory, and a battlefield.",
    "image": "https://hotandjuicypodcast.com/images/blog-ugali-diaries-kenyan-food.jpg",
    "type": "article"
  },
  "/blog/post-003": {
    "title": "Long-Distance Love in the Diaspora: Hard Truths Nobody Talks About — Hot & Juicy Blog",
    "description": "Loving someone from 4,000 kilometres away is romantic until it is not. Time zones, trust, and the loneliness nobody prepares you for.",
    "image": "https://hotandjuicypodcast.com/images/blog-long-distance-love-diaspora-j.jpg",
    "type": "article"
  },
  "/blog/post-004": {
    "title": "Building Wealth Abroad: How Kenyans in the Gulf Are Winning — Hot & Juicy Blog",
    "description": "From side hustles to full-blown businesses — the untold story of Kenyan entrepreneurship in Qatar, Saudi, and the UAE.",
    "image": "https://hotandjuicypodcast.com/images/blog-business-building-wealth-abroad-02.jpg",
    "type": "article"
  },
  "/blog/post-005": {
    "title": "Doha Unfiltered: A Kenyan's Guide to Surviving and Thriving in Qatar — Hot & Juicy Blog",
    "description": "From finding the best nyama choma spots to navigating labour laws — everything you wish someone told you before you moved to Doha.",
    "image": "https://hotandjuicypodcast.com/images/blog-doha-unfiltered-kenyans-guide-02.jpg",
    "type": "article"
  },
  "/blog/post-006": {
    "title": "From Listener to Family: How Hot & Juicy Built a Community in Doha — Hot & Juicy Blog",
    "description": "It started as three friends recording in a living room. Then the messages started coming — and we realised the podcast was never just about us.",
    "image": "https://hotandjuicypodcast.com/images/blog-from-listener-to-family-02.jpg",
    "type": "article"
  }
};
