/* AUTO-GENERATED by scripts/build-meta.mjs — do not edit by hand. */
export default {
  "/episodes/ep-001": {
    "title": "Kenyans in Dubai: What Really Happens When Jobs Disappear? — Hot & Juicy Podcast",
    "description": "Kemboi Kujiuza joins the table for a raw conversation about life in Dubai — what really happens when jobs disappear, and how the community survives it.",
    "image": "https://i.ytimg.com/vi/R0Z3ltddn94/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-002": {
    "title": "How to Dress & Look Expensive Without Breaking the Bank — Hot & Juicy Podcast",
    "description": "Style and confidence talk — how to dress well and look expensive without breaking the bank. Fashion, fit, and looking the part on a budget.",
    "image": "https://i.ytimg.com/vi/hdsLogtyQjE/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-003": {
    "title": "Andrew Kibe's Advice to the Youth That Every Young Kenyan Needs to Hear — Hot & Juicy Podcast",
    "description": "Andrew Kibe pulls no punches with advice every young Kenyan needs to hear — career, money, relationships, and cutting through the noise.",
    "image": "https://i.ytimg.com/vi/ADvNYcpFo0w/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/episodes/ep-011": {
    "title": "Andy Deh Finally Apologizes After Being Cancelled Over Natalie Githinji P2 Claims — Hot & Juicy Podcast",
    "description": "Andy Deh finally apologizes after being cancelled over the Natalie Githinji P2 claims — the full story, the apology, and where things stand now.",
    "image": "https://i.ytimg.com/vi/FEnrx9ipqGw/maxresdefault.jpg",
    "type": "video.episode"
  },
  "/blog/post-001": {
    "title": "What It Really Means to Be Kenyan in Doha — Hot & Juicy Blog",
    "description": "Living between two worlds — the warmth of Nairobi and the ambition of Qatar. Here's what nobody tells you about the expat experience.",
    "image": "https://hotandjuicypodcast.com/images/blog-what-it-means-kenyan-doha.jpg",
    "type": "article"
  },
  "/blog/post-002": {
    "title": "The Ugali Diaries: What Kenyan Food Says About Who We Are — Hot & Juicy Blog",
    "description": "From the great ugali debate to the politics of chapati at weddings — Kenyan food is more than fuel. It is identity, memory, and a battlefield.",
    "image": "https://hotandjuicypodcast.com/images/blog-ugali-diaries-kenyan-food.jpg",
    "type": "article"
  },
  "/blog/post-003": {
    "title": "Long-Distance Love in the Diaspora: Hard Truths Nobody Talks About — Hot & Juicy Blog",
    "description": "Loving someone from 4,000 kilometres away is romantic until it is not. Time zones, trust, and the loneliness nobody prepares you for.",
    "image": "https://hotandjuicypodcast.com/images/blog-long-distance-love-diaspora-j.jpg",
    "type": "article"
  },
  "/blog/post-004": {
    "title": "Building Wealth Abroad: How Kenyans in the Gulf Are Winning — Hot & Juicy Blog",
    "description": "From side hustles to full-blown businesses — the untold story of Kenyan entrepreneurship in Qatar, Saudi, and the UAE.",
    "image": "https://hotandjuicypodcast.com/images/blog-business-building-wealth-abroad-02.jpg",
    "type": "article"
  },
  "/blog/post-005": {
    "title": "Doha Unfiltered: A Kenyan's Guide to Surviving and Thriving in Qatar — Hot & Juicy Blog",
    "description": "From finding the best nyama choma spots to navigating labour laws — everything you wish someone told you before you moved to Doha.",
    "image": "https://hotandjuicypodcast.com/images/blog-doha-unfiltered-kenyans-guide-02.jpg",
    "type": "article"
  },
  "/blog/post-006": {
    "title": "From Listener to Family: How Hot & Juicy Built a Community in Doha — Hot & Juicy Blog",
    "description": "It started as three friends recording in a living room. Then the messages started coming — and we realised the podcast was never just about us.",
    "image": "https://hotandjuicypodcast.com/images/blog-from-listener-to-family-02.jpg",
    "type": "article"
  }
};
