/**
 * Vercel Edge Middleware — server-side social/SEO meta for episode & post pages.
 *
 * Deep links (/episodes/ep-###, /blog/post-###) are served by client-side
 * templates whose <head> only knows placeholders. Scrapers (WhatsApp, X,
 * Facebook, iMessage) and non-JS crawlers never run the JS, so shared links
 * used to show a generic card. This middleware swaps title/description/
 * canonical/og/twitter tags in the HTML before it leaves the edge, using
 * metas.js generated by scripts/build-meta.mjs.
 */
import metas from './metas.js';

const SITE = 'https://hotandjuicypodcast.com';

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
}

function injectMeta(html, path, m) {
  const canonical = SITE + path;
  return html
    .replace(/<title(?:\s[^>]*)?>[\s\S]*?<\/title>/i, `<title>${esc(m.title)}</title>`)
    .replace(/<meta name="description"(?:\s[^>]*)?>/i, `<meta name="description" content="${esc(m.description)}">`)
    .replace(/<link rel="canonical"(?:\s[^>]*)?>/i, `<link rel="canonical" href="${canonical}">`)
    .replace(/<meta property="og:url"(?:\s[^>]*)?>/i, `<meta property="og:url" content="${canonical}">`)
    .replace(/<meta property="og:title"(?:\s[^>]*)?>/i, `<meta property="og:title" content="${esc(m.title)}">`)
    .replace(/<meta property="og:description"(?:\s[^>]*)?>/i, `<meta property="og:description" content="${esc(m.description)}">`)
    .replace(/<meta property="og:image"(?:\s[^>]*)?>/i, `<meta property="og:image" content="${esc(m.image)}">`)
    .replace(/<meta property="og:type"(?:\s[^>]*)?>/i, `<meta property="og:type" content="${esc(m.type)}">`)
    .replace(/<meta name="twitter:title"(?:\s[^>]*)?>/i, `<meta name="twitter:title" content="${esc(m.title)}">`)
    .replace(/<meta name="twitter:description"(?:\s[^>]*)?>/i, `<meta name="twitter:description" content="${esc(m.description)}">`)
    .replace(/<meta name="twitter:image"(?:\s[^>]*)?>/i, `<meta name="twitter:image" content="${esc(m.image)}">`);
}

export default async function middleware(request) {
  const { pathname } = new URL(request.url);
  const m = metas[pathname];
  if (!m) return; // fall through to the normal static/rewrite pipeline

  // Fetch the underlying template. The subrequest re-enters this middleware,
  // misses the metas lookup, and falls through to the static template file.
  const template = pathname.startsWith('/episodes/')
    ? '/episodes/episode-template.html'
    : '/blog/post-template.html';
  const res = await fetch(new URL(template, request.url));
  let html = await res.text();
  html = injectMeta(html, pathname, m);

  return new Response(html, {
    status: 200,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'cache-control': 'public, max-age=0, must-revalidate',
      'x-meta-injected': pathname,
    },
  });
}

export const config = {
  matcher: ['/episodes/:slug*', '/blog/:slug*'],
};
