/**
 * build-meta.mjs — generates metas.js for the edge middleware.
 *
 * Reads episode/post data out of js/data.js (plain browser script, so we
 * evaluate it with a minimal window stub) and writes one entry per
 * episode/post with the fields social scrapers need.
 *
 * Run: node scripts/build-meta.mjs
 * Output: metas.js (ES module — imported by middleware.js at the edge;
 * a .js module is used rather than JSON import assertions for runtime
 * compatibility).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = readFileSync(join(root, 'js', 'data.js'), 'utf8');

// data.js is a browser global script; evaluate it in a stubbed scope and
// capture the arrays it declares.
const stub = `
  const window = { location: { pathname: '/', search: '' } };
  const document = { addEventListener() {}, querySelector() { return null; } };
  const navigator = {};
  ${source}
  ;__capture({ episodes, blogPosts });
`;
const { episodes, blogPosts } = (() => {
  let captured;
  const __capture = (data) => { captured = data; };
  new Function('__capture', stub)(__capture);
  return captured;
})();

const SITE = 'https://hotandjuicypodcast.com';
const meta = {};

for (const ep of episodes) {
  const title = `${ep.title} — Hot & Juicy Podcast`;
  const desc = (ep.description || ep.desc || `Episode ${ep.number} of Hot & Juicy Podcast: real conversations on food, dating, diaspora life and culture.`)
    .replace(/\s+/g, ' ').trim().slice(0, 158);
  meta[`/episodes/${ep.id}`] = {
    title,
    description: desc,
    image: ep.youtubeId
      ? `https://i.ytimg.com/vi/${ep.youtubeId}/maxresdefault.jpg`
      : `${SITE}/images/og-default.jpg`,
    type: 'video.episode',
  };
}

for (const post of blogPosts) {
  const title = `${post.title} — Hot & Juicy Blog`;
  const desc = (post.excerpt || post.description || post.desc || 'From the Hot & Juicy blog.')
    .replace(/\s+/g, ' ').trim().slice(0, 158);
  meta[`/blog/${post.id}`] = {
    title,
    description: desc,
    image: post.image ? `${SITE}/images/${post.image}` : `${SITE}/images/og-default.jpg`,
    type: 'article',
  };
}

const js = `/* AUTO-GENERATED by scripts/build-meta.mjs — do not edit by hand. */\nexport default ${JSON.stringify(meta, null, 2)};\n`;
writeFileSync(join(root, 'metas.js'), js);
writeFileSync(join(root, 'metas.json'), JSON.stringify(meta, null, 2) + '\n');
console.log(`metas written: ${Object.keys(meta).length} entries`);
